-- ============================================================
-- database/dcl/roles_and_grants.sql
-- Oracle DCL (Data Control Language) Roles and Privilege Grants
-- ============================================================

-- 1. Create Application Database Roles
CREATE ROLE ROLE_PORTAL_STUDENT;
CREATE ROLE ROLE_PORTAL_RECRUITER;
CREATE ROLE ROLE_PORTAL_ADMIN;

-- 2. Grant Privileges for Student Role
-- Students can read program/drive info and manage their own applications
GRANT SELECT ON PROGRAM TO ROLE_PORTAL_STUDENT;
GRANT SELECT ON BATCH TO ROLE_PORTAL_STUDENT;
GRANT SELECT ON PLACEMENT_DRIVE TO ROLE_PORTAL_STUDENT;
GRANT SELECT ON V_STUDENT_APPLICATIONS TO ROLE_PORTAL_STUDENT;
GRANT SELECT ON V_OFFER_SUMMARY TO ROLE_PORTAL_STUDENT;
GRANT EXECUTE ON REGISTER_STUDENT_PROGRAM TO ROLE_PORTAL_STUDENT;
GRANT EXECUTE ON APPLY_FOR_DRIVE TO ROLE_PORTAL_STUDENT;
GRANT EXECUTE ON GET_STUDENT_APPLICATION_COUNT TO ROLE_PORTAL_STUDENT;

-- 3. Grant Privileges for Recruiter Role
-- Recruiters can manage jobs, drives, review applications, and schedule interviews
GRANT SELECT, INSERT, UPDATE ON JOB_COMPANY TO ROLE_PORTAL_RECRUITER;
GRANT SELECT, INSERT, UPDATE ON PLACEMENT_DRIVE TO ROLE_PORTAL_RECRUITER;
GRANT SELECT ON STUDENT TO ROLE_PORTAL_RECRUITER;
GRANT SELECT, UPDATE ON APPLICATION TO ROLE_PORTAL_RECRUITER;
GRANT SELECT, INSERT, UPDATE ON INTERVIEW TO ROLE_PORTAL_RECRUITER;
GRANT EXECUTE ON SCHEDULE_INTERVIEW TO ROLE_PORTAL_RECRUITER;
GRANT EXECUTE ON ISSUE_OFFER TO ROLE_PORTAL_RECRUITER;
GRANT EXECUTE ON GET_ELIGIBLE_STUDENTS TO ROLE_PORTAL_RECRUITER;
GRANT EXECUTE ON PKG_PLACEMENT_REPORTS TO ROLE_PORTAL_RECRUITER;

-- 4. Grant Privileges for Admin Role
-- Administrators have full schema DML & execution rights
GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROGRAM TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON BATCH TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMPANY TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLACEMENT_DRIVE TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON APPLICATION TO ROLE_PORTAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON OFFER_LETTER TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON REGISTER_STUDENT_PROGRAM TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON APPLY_FOR_DRIVE TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON SCHEDULE_INTERVIEW TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON ISSUE_OFFER TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON GET_PLACEMENT_RATE TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON GET_AVERAGE_PACKAGE TO ROLE_PORTAL_ADMIN;
GRANT EXECUTE ON PKG_PLACEMENT_REPORTS TO ROLE_PORTAL_ADMIN;

-- 5. Demonstrate REVOKE capability
-- Example: Revoke direct table DELETE permission from Recruiter role
REVOKE DELETE ON APPLICATION FROM ROLE_PORTAL_RECRUITER;
