-- ============================================================
-- V2__constraints.sql
-- Primary Keys, Foreign Keys, Unique Keys, and Check Constraints
-- (Updated per Locked Decision 1: Program-Scoped Batch_No)
-- ============================================================

-- ------------------------------------------------------------
-- PRIMARY KEYS
-- ------------------------------------------------------------
ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY (Student_Id);
ALTER TABLE STUDENT_PHONE ADD CONSTRAINT PK_STUDENT_PHONE PRIMARY KEY (Student_Id, Phone);
ALTER TABLE PROGRAM ADD CONSTRAINT PK_PROGRAM PRIMARY KEY (Program_Id);
ALTER TABLE REGISTERS ADD CONSTRAINT PK_REGISTERS PRIMARY KEY (Student_Id, Program_Id);
ALTER TABLE BATCH ADD CONSTRAINT PK_BATCH PRIMARY KEY (Program_Id, Batch_No);
ALTER TABLE BATCH_PROGRAM ADD CONSTRAINT PK_BATCH_PROGRAM PRIMARY KEY (Program_Id, Batch_No);
ALTER TABLE ATTENDS ADD CONSTRAINT PK_ATTENDS PRIMARY KEY (Student_Id, Program_Id, Batch_No);
ALTER TABLE BATCH_TITLE_PROGRAM ADD CONSTRAINT PK_BATCH_TITLE_PROGRAM PRIMARY KEY (Program_Id, Batch_No, Title);
ALTER TABLE ASSESSMENT ADD CONSTRAINT PK_ASSESSMENT PRIMARY KEY (Assessment_Id);
ALTER TABLE EMAIL_COMPANY ADD CONSTRAINT PK_EMAIL_COMPANY PRIMARY KEY (Email);
ALTER TABLE COMPANY ADD CONSTRAINT PK_COMPANY PRIMARY KEY (Company_Id);
ALTER TABLE COMPANY_PHONE ADD CONSTRAINT PK_COMPANY_PHONE PRIMARY KEY (Company_Id, Phone_No);
ALTER TABLE JOB_COMPANY ADD CONSTRAINT PK_JOB_COMPANY PRIMARY KEY (Job_Title);
ALTER TABLE PLACEMENT_DRIVE ADD CONSTRAINT PK_PLACEMENT_DRIVE PRIMARY KEY (Drive_Id);
ALTER TABLE STUDENT_DAILY_ROUTINE_DRIVE ADD CONSTRAINT PK_STUDENT_ROUTINE PRIMARY KEY (Student_Id, Apply_Date);
ALTER TABLE APPLICATION ADD CONSTRAINT PK_APPLICATION PRIMARY KEY (Application_Id);
ALTER TABLE INTERVIEWER_ROUND ADD CONSTRAINT PK_INTERVIEWER_ROUND PRIMARY KEY (Interviewer_Name);
ALTER TABLE INTERVIEW ADD CONSTRAINT PK_INTERVIEW PRIMARY KEY (Application_Id, Interviewer_Name);
ALTER TABLE OFFER_LETTER ADD CONSTRAINT PK_OFFER_LETTER PRIMARY KEY (Offer_Id);
ALTER TABLE APPLICATION_AUDIT ADD CONSTRAINT PK_APP_AUDIT PRIMARY KEY (Audit_Id);
ALTER TABLE PORTAL_USER ADD CONSTRAINT PK_PORTAL_USER PRIMARY KEY (User_Id);

-- ------------------------------------------------------------
-- UNIQUE CONSTRAINTS
-- ------------------------------------------------------------
ALTER TABLE STUDENT ADD CONSTRAINT UQ_STUDENT_EMAIL UNIQUE (Email);
ALTER TABLE OFFER_LETTER ADD CONSTRAINT UQ_OFFER_APPLICATION UNIQUE (Application_Id);
ALTER TABLE PORTAL_USER ADD CONSTRAINT UQ_PORTAL_USERNAME UNIQUE (Username);

-- ------------------------------------------------------------
-- FOREIGN KEYS
-- ------------------------------------------------------------
ALTER TABLE STUDENT_PHONE ADD CONSTRAINT FK_STUPHONE_STUDENT 
    FOREIGN KEY (Student_Id) REFERENCES STUDENT (Student_Id) ON DELETE CASCADE;

ALTER TABLE REGISTERS ADD CONSTRAINT FK_REGISTERS_STUDENT 
    FOREIGN KEY (Student_Id) REFERENCES STUDENT (Student_Id) ON DELETE CASCADE;

ALTER TABLE REGISTERS ADD CONSTRAINT FK_REGISTERS_PROGRAM 
    FOREIGN KEY (Program_Id) REFERENCES PROGRAM (Program_Id) ON DELETE CASCADE;

ALTER TABLE BATCH ADD CONSTRAINT FK_BATCH_PROGRAM_DEF 
    FOREIGN KEY (Program_Id) REFERENCES PROGRAM (Program_Id) ON DELETE CASCADE;

ALTER TABLE BATCH_PROGRAM ADD CONSTRAINT FK_BP_BATCH 
    FOREIGN KEY (Program_Id, Batch_No) REFERENCES BATCH (Program_Id, Batch_No) ON DELETE CASCADE;

ALTER TABLE ATTENDS ADD CONSTRAINT FK_ATTENDS_STUDENT 
    FOREIGN KEY (Student_Id) REFERENCES STUDENT (Student_Id) ON DELETE CASCADE;

ALTER TABLE ATTENDS ADD CONSTRAINT FK_ATTENDS_BATCH 
    FOREIGN KEY (Program_Id, Batch_No) REFERENCES BATCH (Program_Id, Batch_No) ON DELETE CASCADE;

ALTER TABLE BATCH_TITLE_PROGRAM ADD CONSTRAINT FK_BTP_BATCH 
    FOREIGN KEY (Program_Id, Batch_No) REFERENCES BATCH (Program_Id, Batch_No) ON DELETE CASCADE;

ALTER TABLE ASSESSMENT ADD CONSTRAINT FK_ASSESSMENT_BTP 
    FOREIGN KEY (Program_Id, Batch_No, Title) REFERENCES BATCH_TITLE_PROGRAM (Program_Id, Batch_No, Title) ON DELETE CASCADE;

ALTER TABLE COMPANY ADD CONSTRAINT FK_COMPANY_EMAIL 
    FOREIGN KEY (Email) REFERENCES EMAIL_COMPANY (Email) ON DELETE CASCADE;

ALTER TABLE COMPANY_PHONE ADD CONSTRAINT FK_COMPHONE_COMPANY 
    FOREIGN KEY (Company_Id) REFERENCES COMPANY (Company_Id) ON DELETE CASCADE;

ALTER TABLE JOB_COMPANY ADD CONSTRAINT FK_JOB_COMPANY 
    FOREIGN KEY (Company_Id) REFERENCES COMPANY (Company_Id) ON DELETE CASCADE;

ALTER TABLE PLACEMENT_DRIVE ADD CONSTRAINT FK_DRIVE_JOB 
    FOREIGN KEY (Job_Title) REFERENCES JOB_COMPANY (Job_Title) ON DELETE CASCADE;

ALTER TABLE STUDENT_DAILY_ROUTINE_DRIVE ADD CONSTRAINT FK_ROUTINE_STUDENT 
    FOREIGN KEY (Student_Id) REFERENCES STUDENT (Student_Id) ON DELETE CASCADE;

ALTER TABLE STUDENT_DAILY_ROUTINE_DRIVE ADD CONSTRAINT FK_ROUTINE_DRIVE 
    FOREIGN KEY (Drive_Id) REFERENCES PLACEMENT_DRIVE (Drive_Id) ON DELETE CASCADE;

ALTER TABLE APPLICATION ADD CONSTRAINT FK_APP_ROUTINE 
    FOREIGN KEY (Student_Id, Apply_Date) REFERENCES STUDENT_DAILY_ROUTINE_DRIVE (Student_Id, Apply_Date) ON DELETE CASCADE;

ALTER TABLE INTERVIEW ADD CONSTRAINT FK_INTERVIEW_APP 
    FOREIGN KEY (Application_Id) REFERENCES APPLICATION (Application_Id) ON DELETE CASCADE;

ALTER TABLE INTERVIEW ADD CONSTRAINT FK_INTERVIEW_ROUND 
    FOREIGN KEY (Interviewer_Name) REFERENCES INTERVIEWER_ROUND (Interviewer_Name) ON DELETE CASCADE;

ALTER TABLE OFFER_LETTER ADD CONSTRAINT FK_OFFER_APP 
    FOREIGN KEY (Application_Id) REFERENCES APPLICATION (Application_Id) ON DELETE CASCADE;

-- ------------------------------------------------------------
-- CHECK CONSTRAINTS
-- ------------------------------------------------------------
ALTER TABLE STUDENT ADD CONSTRAINT CHK_STUDENT_CGPA 
    CHECK (CGPA >= 0.00 AND CGPA <= 10.00);

ALTER TABLE PROGRAM ADD CONSTRAINT CHK_PROGRAM_FEE 
    CHECK (Fee >= 0);

ALTER TABLE PROGRAM ADD CONSTRAINT CHK_PROGRAM_FLAGS 
    CHECK (
        Beginner IN ('Y', 'N') AND 
        Intermediate IN ('Y', 'N') AND 
        Advanced IN ('Y', 'N') AND
        ((CASE WHEN Beginner = 'Y' THEN 1 ELSE 0 END +
          CASE WHEN Intermediate = 'Y' THEN 1 ELSE 0 END +
          CASE WHEN Advanced = 'Y' THEN 1 ELSE 0 END) = 1)
    );

ALTER TABLE ASSESSMENT ADD CONSTRAINT CHK_ASSESSMENT_FLAGS 
    CHECK (
        Beginner IN ('Y', 'N') AND 
        Intermediate IN ('Y', 'N') AND 
        Advanced IN ('Y', 'N') AND
        ((CASE WHEN Beginner = 'Y' THEN 1 ELSE 0 END +
          CASE WHEN Intermediate = 'Y' THEN 1 ELSE 0 END +
          CASE WHEN Advanced = 'Y' THEN 1 ELSE 0 END) = 1)
    );

ALTER TABLE ASSESSMENT ADD CONSTRAINT CHK_ASSESSMENT_MARKS 
    CHECK (Max_Marks > 0);

ALTER TABLE PLACEMENT_DRIVE ADD CONSTRAINT CHK_DRIVE_CGPA 
    CHECK (Min_CGPA >= 0.00 AND Min_CGPA <= 10.00);

ALTER TABLE APPLICATION ADD CONSTRAINT CHK_APP_STATUS 
    CHECK (Status IN ('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'SELECTED', 'OFFERED', 'REJECTED'));

ALTER TABLE INTERVIEW ADD CONSTRAINT CHK_INTERVIEW_RESULT 
    CHECK (Result IN ('PENDING', 'CLEARED', 'REJECTED'));

ALTER TABLE INTERVIEW ADD CONSTRAINT CHK_INTERVIEW_MODE 
    CHECK ("ONLINE" IN ('Y', 'N') AND "OFFLINE" IN ('Y', 'N'));

ALTER TABLE OFFER_LETTER ADD CONSTRAINT CHK_OFFER_CTC 
    CHECK (CTC_LPA > 0);

ALTER TABLE PORTAL_USER ADD CONSTRAINT CHK_USER_ROLE 
    CHECK (Role IN ('ROLE_STUDENT', 'ROLE_RECRUITER', 'ROLE_ADMIN'));
